name: llmeval-tada24
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - numpy=1.26.0
  - pandas=2.1.1
  - scikit-learn=1.3.1
  - matplotlib=3.8.0
  - attrs=23.1.0
  - tqdm=4.66.1
  - notebook=7.0.4
  - hydra-core=1.3.2
  - pyarrow=13.0.0
  - requests=2.31.0
  - cattrs=23.1.2
  - tiktoken=0.5.1
  - tabulate=0.9.0