dataset_name: "wikitables-turl"

# dataset-specific configuration goes here

url: "https://buckeyemailosu-my.sharepoint.com/personal/deng_595_buckeyemail_osu_edu/_layouts/15/download.aspx?SourceUrl=%2Fpersonal%2Fdeng%5F595%5Fbuckeyemail%5Fosu%5Fedu%2FDocuments%2FBuckeyeBox%20Data%2FTURL%2Fdata%2Ftrain%2Etable%5Fcol%5Ftype%2Ejson"